DROP TABLE IF EXISTS champ_info;
CREATE TABLE IF NOT EXISTS champ_info (
    name VARCHAR(256) PRIMARY KEY,
    traits TEXT
);

DROP TABLE IF EXISTS trait_info;
CREATE TABLE IF NOT EXISTS trait_info (
    name VARCHAR(256) PRIMARY KEY,
    description TEXT
);

INSERT INTO champ_info (name, traits) VALUES
('Alistar', 'Golden Ox,Bruiser'),
('Annie', 'Golden Ox,A.M.P.'),
('Aphelios', 'Golden Ox,Marksman'),
('Aurora', 'Anima Squad,Dynamo'),
('Brand', 'Street Demon,Techie'),
('Braum', 'Syndicate,Vanguard'),
("Cho'Gath", 'BoomBots,Bruiser'),
('Darius', 'Syndicate,Bruiser'),
('Dr.Mundo', 'Street Demon,Bruiser,Slayer'),
('Draven', 'Cypher,Rapidfire'),
('Ekko', 'Street Demon,Strategist'),
('Elise', 'Nitro,Dynamo'),
('Fiddlesticks', 'BoomBots,Techie'),
('Galio', 'Cypher,Bastion'),
('Garen', 'God of the Net'),
('Gragas', 'Divinicorp,Bruiser'),
('Graves', 'Golden Ox,Executioner'),
('Illaoi', 'Anima Squad,Bastion'),
('Jarvan IV', 'Golden Ox,Vanguard,Slayer'),
('Jax', 'Exotech,Bastion'),
('Jhin', 'Exotech,Marksman,Dynamo'),
('Jinx', 'Street Demon,Marksman'),
('Kindred', 'Nitro,Rapidfire,Marksman'),
('Kobuko', 'Cyberboss,Bruiser'),
("Kog'Maw", 'BoomBots,Rapidfire'),
('LeBlanc', 'Cypher,Strategist'),
('Leona', 'Anima Squad,Vanguard'),
('Miss Fortune', 'Syndicate,Dynamo'),
('Mordekaiser', 'Exotech,Bruiser,Techie'),
('Morgana', 'Divinicorp,Dynamo'),
('Naafiri', 'Exotech,A.M.P.'),
('Neeko', 'Street Demon,Strategist'),
('Nidalee', 'Nitro,A.M.P.'),
('Poppy', 'Cyberboss,Bastion'),
('Renekton', 'Overlord,Divinicorp,Bastion'),
('Rengar', 'Street Demon,Executioner'),
('Rhaast', 'Divinicorp,Vanguard'),
('Samira', 'Street Demon,A.M.P.'),
('Sejuani', 'Exotech,Bastion'),
('Senna', 'Divinicorp,Slayer'),
('Seraphine', 'Anima Squad,Techie'),
('Shaco', 'Syndicate,Slayer'),
('Shyvana', 'Nitro,Bastion,Techie'),
('Skarner', 'BoomBots,Vanguard'),
('Sylas', 'Anima Squad,Vanguard'),
('Twisted Fate', 'Syndicate,Rapidfire'),
('Urgot', 'BoomBots,Executioner'),
('Varus', 'Exotech,Executioner'),
('Vayne', 'Anima Squad,Slayer'),
('Veigar', 'Cyberboss,Techie'),
('Vex', 'Divinicorp,Executioner'),
('Vi', 'Cypher,Vanguard'),
('Viego', 'Soul Killer,Golden Ox,Techie'),
('Xayah', 'Anima Squad,Marksman'),
('Yuumi', 'Anima Squad,A.M.P.,Strategist'),
('Zac', 'Virus'),
('Zed', 'Cypher,Slayer'),
('Zeri', 'Exotech,Rapidfire'),
('Ziggs', 'Cyberboss,Strategist'),
('Zyra', 'Street Demon,Techie');

INSERT INTO trait_info (name, description) VALUES
('Anima Squad','At each tier, a random Anima Squad champion fires an extra weapon periodically. Anima Squad champions also gain bonus Armor, Magic Resist, and Damage Amp.'),
('BoomBots','BoomBots champions fire a magic damage missile at an enemy after every 400 damage they deal, and 8 PERCENT of damage they take is added to this missiles damage.'),
('Cyberboss','The strongest Cyberboss champion transforms into its final form, gaining bonus Health and Ability Power, and its ability hits additional enemies.'),
('Cypher','Cypher champions accumulate Intel by losing rounds (and a bit from kills). They can trade Intel for loot one time, after which Cypher champions gain bonus Attack Damage and Ability Power.'),
('Divinicorp','Each Divinicorp champion grants a unique stat to your team (and double to themselves), which increases with more Divinicorp champions on the field.'),
('Exotech','Exotech champions can equip special Exotech-only items and gain bonus Health and Attack Speed for each such item equipped.'),
('God of the Net','After 2 combats, opens an Armory of Trait Mods to give a champion the benefit of a trait (without contributing). Each mod taken increases the rounds needed for the next; champions can only have one mod.'),
('Golden Ox','Golden Ox champions gain Damage Amp and can drop gold on kills. Spending gold on rerolls or XP permanently increases their Damage Amp (if they fought last round).'),
('Nitro','Nitro champions generate Chrome each round based on their star level, fueling a robot ally. At 200 Chrome, the robot ally upgrades into a more powerful form.'),
('Overlord','The Overlord champion bites the unit behind him, dealing 40 PERCENT of their max Health as true damage and absorbing 40 PERCENT of their Health and 33 PERCENT of their Attack Damage.'),
('Soul Killer','The Soul Killer champion creates a hologram of the highest-cost enemy he helped kill last round. The hologram has very high Health and deals significant damage (scaling with the champions star level).'),
('Street Demon','Allies in painted hexes gain bonus Health, Ability Power, and Attack Damage (50 PERCENT more on signature hexes). Street Demon champions double all these bonuses.'),
('Syndicate','Grants a Kingpin hat that upgrades a chosen Syndicate champions ability. Syndicate champions also gain bonus Health and Damage Amp.'),
('Virus','The Virus champion infects the shop with a 10 PERCENT chance to spawn a bloblet. Buying the bloblet permanently increases that champions Health and Ability Power.'),
('A.M.P.','A.M.P. champions get unique ability upgrades (gain Amp) and also gain bonus Health.'),
('Bastion','All allies gain Armor and Magic Resist; Bastion champions gain more, and double their bonus for the first 10 seconds of combat.'),
('Bruiser','All allies gain bonus Health; Bruiser champions gain an additional percentage increase to their max Health.'),
('Dynamo','Every 3 seconds your team gains Mana; Dynamo champions gain twice as much Mana.'),
('Executioner','Executioner abilities can critically strike, and Executioners gain increased Critical Chance and Critical Damage. If a target is below 30 PERCENT Health, Executioners deal double bonus critical damage.'),
('Marksman','Marksman champions gain bonus Attack Damage, which doubles after 8 seconds of combat.'),
('Rapidfire','Your team gains bonus Attack Speed; Rapidfire champions gain stacking Attack Speed on each attack.'),
('Slayer','Slayer champions gain bonus Attack Damage and Omnivamp. Excess healing from their Omnivamp is redirected to heal the allied Slayer with the lowest health.'),
('Strategist','At combat start, back-row allies gain bonus damage and front-row allies gain damage reduction. Strategist champions gain triple these bonuses.'),
('Techie','Techie champions gain bonus Ability Power, and enemies hit by their abilities deal reduced damage for a short duration.'),
('Vanguard','Vanguard champions gain 10 PERCENT increased durability (damage reduction) while shielded, and they gain a shield at the start of combat and upon reaching 50 PERCENT Health.');
